# Generated by Django 2.0.5 on 2018-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
