# Generated by Django 2.0.5 on 2018-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180811_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='special',
            field=models.CharField(default='06', max_length=2000),
        ),
        migrations.AlterField(
            model_name='patient',
            name='assurance',
            field=models.CharField(default='Aucune', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(default='Aucune', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='special',
            field=models.CharField(default='Aucune', max_length=2000),
        ),
    ]
