# Generated by Django 2.0.5 on 2018-08-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180811_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='special',
            field=models.CharField(blank=True, default='06', max_length=2000, null=True),
        ),
    ]
